### ISSUE TITLE
Tramp hangs on "Tramp: Found remote shell prompt on `alpine'" on alpine linux

### ISSUE THREAD

**Issue by Tritlo** [emacs-pe/docker-tramp.el#11]
I'm having an issue when trying to connect to an alpine linux container. It hangs on "Tramp: Found remote shell prompt on `alpine'" .

To reproduce:
    
    # Start an alpine container
    $ docker run -it --rm --name alpine alpine sh

Then try to connect to that container with

    /docker:alpine:/

It seems it gets stuck in a loop waiting for process output, with this over and over:

    20:00:33.498508 tramp-get-connection-property (7) # check-remote-echo nil
    20:00:33.498620 tramp-get-connection-property (7) # check-remote-echo nil
    20:00:33.498751 tramp-get-connection-property (7) # gateway nil
    20:00:34.499380 tramp-accept-process-output (10) # *tramp/docker alpine* run *tramp/docker alpine*
    exec env ENV='' HISTFILE=/dev/null PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='
    
    ' /bin/sh 
    #$ [6n

**Comment by Tritlo** [comment]
My current workaround is to install `bash` and symlink `/bin/sh` to that (is usually linked to busybox in alpine), but that is less than optimal.

**Comment by marsam** [comment]
Hi:

I can reproduce this. It's a bug in busybox in the alpine image, it sends the escape sequence ` [6n` which tramp doesn't recognize. This regex can't be customized, so it can't be fixed from our end.

You can apply the following patch to tramp to make it work

```patch
diff --git a/lisp/net/tramp-sh.el b/lisp/net/tramp-sh.el
index bff6ec3..45eaa92 100644
--- a/lisp/net/tramp-sh.el
+++ b/lisp/net/tramp-sh.el
@@ -5089,7 +5089,7 @@ tramp-wait-for-output
   (with-current-buffer (process-buffer proc)
     (let* (;; Initially, `tramp-end-of-output' is "#$ ".  There might
       ;; be leading escape sequences, which must be ignored.
-      (regexp (format "[^#$\n]*%s\r?$" (regexp-quote tramp-end-of-output)))
+      (regexp (format "[^#$\n]*%s\r?\\(\x1b\\[6n\\)?$" (regexp-quote tramp-end-of-output)))
       ;; Sometimes, the commands do not return a newline but a
       ;; null byte before the shell prompt, for example "git
       ;; ls-files -c -z ...".
```

**Comment by Tritlo** [comment]
So this has been fixed in tramp itself, and it will be released in version 2.3.0.

**Comment by marsam** [comment]
Hi, sorry for the late response. Thanks for following this up.

Seems fixed in [tramp](http://git.savannah.gnu.org/cgit/tramp.git/commit/?id=98a511248a9405848ed44de48a565b0b725af82c) and is going to be in [Emacs 25.1](https://github.com/emacs-mirror/emacs/commit/062757dca01cff127583438ae16237af55b6253c#diff-72db4b312d33d81b4f65b8e6360f91daR5012)

**Comment by mwolson** [comment]
I've confirmed that tramp 2.3.0 does fix it, however that version did not get included with Emacs 25.1, so it's still broken there. Manually installing the correct version of tramp is needed to fix.

**Comment by marsam** [comment]
@mwolson can you try https://github.com/emacs-pe/docker-tramp.el#tramp-hangs-on-alpine-container? tell if doesn't work

**Comment by mwolson** [comment]
@marsam it's missing a `(provide 'docker-tramp-compat)` line at the end. When I add that, I then get the error `tramp-file-name-handler: Symbol’s value as variable is void: tramp-device-escape-sequence-regexp`.

**Comment by marsam** [comment]
Can you try again please

**Comment by mwolson** [comment]
It's still missing the `(provide 'docker-tramp-compat)` line. Once I add that, it seems to work.

**Comment by marsam** [comment]
I added the `provide` line, should work now. Thanks for your help!

**Comment by polsar88** [comment]
The regexp also needs to take into account multiple occurrences of `tramp-end-of-output` when connecting from Windows to Mac OS using plink. [See the full explanation here](https://emacs.stackexchange.com/questions/38610/tramp-on-windows-connects-to-linux-but-not-to-osx-macos/41553#41553)
